n=input('Digite algo:')
print ('O tipo primitivo desse valor é', type(n))
print ('Só tem espaços?', n.isspace())
print ('É um numero?', n.isnumeric())
print ('É alfanúmerico?', n.isalnum())
print ('Está em maiúscula?', n.isupper())
print ('Está em mibúscola?', n.islower())
print ('Está capitalizada?', n.istitle())