n1=int(input('Digite um valor:'))
n2=int(input('Digite outro:'))
s=(n1+n2)
sub=(n1-n2)
m=(n1*n2)
d=(n1/n2)
di=(n1//n2)
e=(n1**n2)
print('A soma é {} a subtração é {} a multiplacação é {}'.format(s, sub, m))
print('A divisão é {:.2f} a divisão inteira é {} a potência é {:.2f}'. format(d, di, e))